apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vite-frontend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/AV295/Solar_Energy_Tracker_DevOps.git
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
