apiVersion: apps/v1
kind: Deployment
metadata:
  name: vite-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vite-frontend
  template:
    metadata:
      labels:
        app: vite-frontend
    spec:
      containers:
        - name: vite-frontend
          image: my-vite-app
          imagePullPolicy: Never     # <--- ADD THIS LINE
          ports:
            - containerPort: 80
