apiVersion: v1
kind: Service
metadata:
  name: vite-service
spec:
  type: NodePort
  selector:
    app: vite-frontend
  ports:
    - port: 80          # Kubernetes service port
      targetPort: 80    # Container's port inside the pod
      nodePort: 30007   # Port exposed on the Minikube host
