name: CI/CD - Vite Frontend App

on:
  push:
    branches: [main]
    paths:
      - 'src/**'
      - 'public/**'
      - 'Dockerfile'
      - '.github/workflows/deploy.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t av80/my-vite-app:latest .

      - name: Push Docker Image
        run: docker push av80/my-vite-app:latest
